from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    SOURCE_UNSUPPORTED = "SOURCE_UNSUPPORTED"
    SOURCE_COMPANION_MISSING = "SOURCE_COMPANION_MISSING"
    SOURCE_CHECKSUM_MISMATCH = "SOURCE_CHECKSUM_MISMATCH"
    METADATA_PARSE_FAILED = "METADATA_PARSE_FAILED"
    MODEL_UNREACHABLE = "MODEL_UNREACHABLE"
    MODEL_AUTH_FAILED = "MODEL_AUTH_FAILED"
    MODEL_SCHEMA_TEST_FAILED = "MODEL_SCHEMA_TEST_FAILED"
    DOMAIN_ROOT_UNRESOLVED = "DOMAIN_ROOT_UNRESOLVED"
    DOMAIN_RUNAWAY_GROWTH = "DOMAIN_RUNAWAY_GROWTH"
    DOMAIN_REVIEW_REQUIRED = "DOMAIN_REVIEW_REQUIRED"
    EXTRACTION_PARSE_FAILED = "EXTRACTION_PARSE_FAILED"
    OUTPUT_DISK_INSUFFICIENT = "OUTPUT_DISK_INSUFFICIENT"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    PURGE_SOURCE_CHANGED = "PURGE_SOURCE_CHANGED"
    PURGE_OUTPUT_UNVERIFIED = "PURGE_OUTPUT_UNVERIFIED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class CorpusSieveError(Exception):
    def __init__(
        self,
        code: ErrorCode,
        message: str,
        detail: dict[str, Any] | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.detail = detail or {}
